### ISSUE TITLE
Explainability

### ISSUE THREAD

**Issue by kywalker-rh** [opendatahub-io/sig-ml-developer-experience#29]
- UI Effort: https://github.com/opendatahub-io/odh-dashboard/issues/1127

**Comment by jkoehler-redhat** [comment]
Is a May 31 completion date for the UX still doable?  My understanding is there are other changes that need to happen and this date may change?

**Comment by vconzola** [comment]
I'm not sure given the recent architecture change. I need to get up with @RobGeada about what exactly the UX requirements are for supporting the TrustyAI operator in each project. If it's as simple as asking the user if they want/need to monitor their models for quality and fairness in a given project, that's likely not too bad. If it involves additional operator configuration, that will be a little trickier.
