### ISSUE TITLE
Data Science Pipelines v2

### ISSUE THREAD

**Issue by kywalker-rh** [opendatahub-io/sig-ml-developer-experience#47]
This is for UX updates to pipelines feature once its been released. Includes any changes needed to support KF Pipelines v2. UI issue for reference: https://github.com/opendatahub-io/odh-dashboard/issues/1575

- https://issues.redhat.com/browse/RHODS-9446
- https://issues.redhat.com/browse/RHODS-8650
- https://github.com/opendatahub-io/odh-dashboard/issues/1519 
- https://github.com/opendatahub-io/odh-dashboard/issues/1285
- https://github.com/opendatahub-io/odh-dashboard/issues/1575
- ~~https://github.com/opendatahub-io/odh-dashboard/issues/1223~~

**Comment by yannnz** [comment]
Include [this issue]( https://github.com/opendatahub-io/odh-dashboard/issues/1223#issuecomment-1614840124) when adding version support.
