### ISSUE TITLE
Habana (accelerator) UX design for end-users

### ISSUE THREAD

**Issue by kywalker-rh** [opendatahub-io/sig-ml-developer-experience#54]
- See requirements doc: https://docs.google.com/document/d/10HOrkt-Vm4Ir_FAggyAttFipiG-L2eZX1wTZLJtLp-c/edit?usp=sharing

- While designing, should also keep in mind Req 2 from Project Wisdom phase 2: https://docs.google.com/document/d/1m1dFOdRnSF1BSt2dT8F9Nxd6YC1mOTS4vX05G9YSEds/edit?usp=sharing
Ideally this design solves for both the Habana and Wisdom use-cases.

**Comment by yannnz** [comment]
This issue is completed. The finalized design link for [end-users](https://www.sketch.com/s/d8550d2f-fae4-44fd-82df-9f400563d459/a/lRkpwKd).
