### ISSUE TITLE
User Experience around enabling User Workload Monitoring for ODH/RHODS

### ISSUE THREAD

**Issue by VedantMahabaleshwarkar** [opendatahub-io/sig-ml-developer-experience#62]
Model Serving is going to be using User Workload Monitoring as the monitoring stack for metrics. 
ADR : https://github.com/opendatahub-io/architecture-decision-records/pull/13 

[Enabling Monitoring for User Workloads](https://docs.openshift.com/container-platform/4.13/monitoring/enabling-monitoring-for-user-defined-projects.html#enabling-monitoring-for-user-defined-projects_enabling-monitoring-for-user-defined-projects) is an Openshift feature that requires cluster admin permissions to enable it. 

We need to consider the User Experience as we transition from the current prometheus to User Workload Monitoring. 
- How do we inform rhods admins of the upcoming change?
- What resources do we need to provide to allow rhods admins to collaborate with cluster admins to enable this at a cluster level?
- If UWM is not enabled, what happens to the metrics UI in odh-dashboard? We need to display some error + remidiation if we detect that user workload monitoring is not enabled

**Comment by andrewballantyne** [comment]
@vconzola @kywalker-rh 

These are good questions and we should think on how we should handle the UI. I suspect a message similar to the Pipeline dependency detection -- but I'll leave that up to you guys if you think it needs to be that bold.

**Comment by vconzola** [comment]
@VedantMahabaleshwarkar Two questions come immediately to mind. (1) Can User Workload Monitoring be enabled by default without a cluster admin having to do anything?, and (2) Is there any reason an ODH/RHODS cluster would not want it enabled?

**Comment by VedantMahabaleshwarkar** [comment]
@vconzola 
> Can User Workload Monitoring be enabled by default without a cluster admin having to do anything? 
On Openshift Dedicated(Managed), the `checkbox` for User Workload Monitoring is enabled by default. 
It is not enabled by default for self-managed as far as I know. 
On existing installs, there is no way to enable the feature without cluster-admin. 

>Is there any reason an ODH/RHODS cluster would not want it enabled?  
That would depend on the overall cluster environment and what other workloads are on the cluster. There's no reason to not want it enabled on a theoretical level but in practice cluster admins might have some concerns like having to allocate more resources to the cluster monitoring stack if necessary. Also, if a cluster does not already have this feature enabled we should not want to enable it without informing or the permissions of the cluster admin since it has the potential to affect cluster resources not related to odh/rhods

**Comment by kywalker-rh** [comment]
To Andrew's comment "I'll leave that up to you guys if you think it needs to be that bold": I think we'd want something that is obvious for Admins from the start, maybe the same (!) as we have for pipelines, but on the Model Serving left nav, but I don't think it should be so obvious for the regular user. For the regular user (who may or may not have anything to do with model monitoring) I would put an alert on the model monitoring page.

Vince and I can talk about it and come up with a specific solution.

**Comment by shalberd** [comment]
Great to see this is gaining tractions, thanks to you all

**Comment by andrewballantyne** [comment]
Closing this issue as @VedantMahabaleshwarkar has used K8s mechanisms and a UX flow is not required to enable UWM.
